version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    env_file:
      - .env
    depends_on:
      - frontend

  frontend:
    build:
      context: ./electrotech
      dockerfile: Dockerfile
    ports:
      - "80:80"
